version: 2.1

jobs:
  build:
   docker:
    - image: circleci/node:8
   steps:
    - checkout
    - run:
        name: Setup Dependencies
        command: |
            cd my-react-app
            npm install
    - run:
        name: Setup Code Climate test-reporter
        command: |
            cd my-react-app
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter	
            chmod +x ./cc-test-reporter
    - run: # run tests
        name: Run Test and coverage
        command: |
             cd my-react-app
             ./cc-test-reporter before-build
             npm test -- --coverage
             ./cc-test-reporter after-build --exit-code $?